language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile
  - npm install -g codecov

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - codecov

